# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ef961c68811f3e1991a5b14554536bb"
name = "payments"
handle = "payments-63"
application_url = "https://lottery-anna-fred-understood.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_payment_customizations"

[auth]
redirect_urls = [
  "https://lottery-anna-fred-understood.trycloudflare.com/auth/callback",
  "https://lottery-anna-fred-understood.trycloudflare.com/auth/shopify/callback",
  "https://lottery-anna-fred-understood.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
